spring:
    datasource:
        url: jdbc:mysql://localhost:3306/todo?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
        password: mysql
    jpa:
        hibernate:
            ddl-auto: update


