spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgresql
        url: jdbc:postgresql://localhost/postgres

    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
        database: postgresql